---
services: docker

env:
  - path: nginx/minimal
    url: http://localhost

  - path: nginx/proxy-to-virtual-path
    url: http://localhost/documentserver-virtual-path

  - path: apache/minimal
    url: http://localhost

  - path: apache/proxy-to-virtual-path
    url: http://localhost/documentserver-virtual-path

  - path: traefik/minimal
    url: http://localhost

script:
  # Go to tests dir
  - cd ${PWD}/tests

  # Run test.
  - ./test.sh
